### ISSUE TITLE
output should mention it's generated

### ISSUE THREAD

**Issue by kawa-kokosowa** [hypatia-software-org/adventuredocs#22]
As a respected coworker said:

> Any generated files that get checked into the repo should be prefixed with a comment that says "DON'T EDIT ME, I WAS GENERATED BY $what AT $when AND YOUR CHANGES WILL GET STOMPED"`

**Comment by e-lisa** [comment]
Submitted PR: https://github.com/lily-mayfield/adventuredocs/pull/24

**Comment by kawa-kokosowa** [comment]
Thanks @e-lisa!
